Models/ErrorViewModel.cs
using System;

namespace AuthTest.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using AuthTest.Models;
using Fastenal.Expo.Web.Helper;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using System.Diagnostics;
using System.Security.Claims;
using System.Threading.Tasks;

namespace AuthTest.Controllers
{
	public class HomeController : Controller
	{
		private IConfiguration configuration;

		protected IConfiguration Configuration => this.configuration ?? (this.configuration = this.HttpContext.RequestServices.GetService<IConfiguration>());

		private Saml.Settings oneLoginSettings;

		protected Saml.Settings OneLoginSettings
		{
			get
			{
				if (this.oneLoginSettings == null)
				{
					this.oneLoginSettings = new Saml.Settings();
					this.Configuration.GetSection("OneLoginSaml").Bind(this.oneLoginSettings);
				}

				return this.oneLoginSettings;
			}
		}

		private OpenId.Settings openIdSettings;

		protected OpenId.Settings OpenIdSettings
		{
			get
			{
				if (this.openIdSettings == null)
				{
					this.openIdSettings = new OpenId.Settings();
					this.Configuration.GetSection("OpenId:B2C").Bind(this.openIdSettings);
				}

				return this.openIdSettings;
			}
		}

		[HttpGet]
		public async Task<IActionResult> Index()
		{
			this.ViewBag.OneLoginUrl = new Saml(this.OneLoginSettings).GetSignInUrl();
			this.ViewBag.B2CUrl = await new OpenId(this.OpenIdSettings).GetSignInUrl("eric@test.com");

			return this.View();
		}

		public IActionResult About()
		{
			ViewData["Message"] = "Your application description page.";

			return View();
		}

		public IActionResult Contact()
		{
			ViewData["Message"] = "Your contact page.";

			return View();
		}

		public IActionResult SaveForm()
		{
			return Json(null);
		}

		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Controllers/IdentityController.cs
using Fastenal.Expo.Web.Helper;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;
using System.Security.Claims;
using System.Threading.Tasks;

namespace AuthTest.Controllers
{
	public class IdentityController : Controller
	{
		private IConfiguration configuration;

		protected IConfiguration Configuration => this.configuration ?? (this.configuration = this.HttpContext.RequestServices.GetService<IConfiguration>());

		private OpenId openId;

		private OpenId OpenId
		{
			get
			{
				if (this.openId == null)
				{
					var settings = new OpenId.Settings();
					this.Configuration.GetSection("OpenId:B2C").Bind(settings);
					this.openId = new OpenId(settings);
				}

				return this.openId;
			}
		}

		private Saml saml;

		private Saml Saml
		{
			get
			{
				if (this.saml == null)
				{
					var settings = new Saml.Settings();
					this.Configuration.GetSection("OneLoginSaml").Bind(settings);
					this.saml = new Saml(settings);
				}

				return this.saml;
			}
		}

		private UserIdentity currentUser;

		private UserIdentity CurrentUser => this.currentUser ?? (this.currentUser = UserIdentity.CreateUserIdentity(this.HttpContext.User.Identity));

		public IdentityController()
		{
		}

		public async Task<IActionResult> SignIn(string email = null)
		{
			if (string.IsNullOrWhiteSpace(email))
			{
				return this.Redirect("/");
			}

			if (email.ToLower().IndexOf("@fastenal.com") > 0)
			{
				return this.Redirect(this.Saml.GetSignInUrl());
			}

			return this.Redirect(await this.OpenId.GetSignInUrl(email));
		}

		public async Task<IActionResult> SignIn2()
		{
			var settings = new OpenId.Settings();
			this.Configuration.GetSection("OpenId:OneLogin").Bind(settings);
			var openId = new OpenId(settings);
			return this.Redirect(await openId.GetSignInUrl());
		}

		[HttpPost, Route("user/signed-in")]
		public async Task<IActionResult> SignedIn()
		{
			UserIdentity user;

			if (this.Request.Form.ContainsKey("SAMLResponse"))
			{
				user = this.Saml.GetUser(this.Request.Form["SAMLResponse"]);
			}
			else if (this.Request.Form.ContainsKey("id_token"))
			{
				user = await this.OpenId.ValidateToken(this.Request.Form["id_token"]);
			}
			else
			{
				return this.RedirectToAction("Index", "Home");
			}

			var cp = new ClaimsPrincipal(user);
			await this.HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, cp, new AuthenticationProperties { IsPersistent = false });
			// Cookie claims needs a page load action to work
			return this.RedirectToAction("Index", "Home");
		}

		[HttpGet]
		public async Task<IActionResult> ResetPassword()
		{
			if (this.CurrentUser.Role == "E")
			{
				return this.RedirectToAction("Index", "Home");
			}

			var url = await this.OpenId.GetPasswordResetUrl(this.CurrentUser.Email);
			return this.Redirect(url);
		}

		[HttpGet]
		public async Task<IActionResult> EditProfile()
		{
			if (this.CurrentUser.Role == "E")
			{
				return this.RedirectToAction("Index", "Home");
			}

			var url = await this.OpenId.GetProfileEditUrl(this.CurrentUser.Email);
			return this.Redirect(url);
		}

		[HttpGet]
		public async Task<IActionResult> SignOut()
		{
			await this.HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

			if (this.CurrentUser.Role == "E")
			{
				var url = this.Saml.GetSignOutUrl(this.CurrentUser.Email);
				return this.Redirect(url);
			}

			return this.RedirectToAction("Index", "Home");
		}
	}
}

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
	ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery-ajax-unobtrusive-3.2.5/dist/jquery.unobtrusive-ajax.js"></script>


<form asp-controller="Home" asp-action="SaveForm" data-ajax="true" data-ajax-method="POST" data-ajax-success="onSuccess">
	<button>Submit</button>
</form>
<script>
	var onSuccess = function () {
		console.log('123');

	}
</script>

Views/Home/Index.cshtml
@{
	ViewData["Title"] = "Home Page";
}
<div class="row">
	<div class="col-md-offset-4 col-md-4">
		<h2>Sign In</h2>
		<form method="get" action="@Url.Action("SignIn", "Identity")">
			<input type="email" name="email" class="form-control" placeholder="Email" />
		</form>
	</div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - AuthTest</title>
	<environment include="Development">
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
		<link rel="stylesheet" href="~/css/site.css" />
	</environment>
	<environment exclude="Development">
		<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
			  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
			  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
		<link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
	</environment>
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a asp-controller="Home" asp-action="Index" class="navbar-brand">AuthTest</a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li><a asp-controller="Home" asp-action="Index">Home</a></li>
				</ul>
				@if (User.Identity.IsAuthenticated)
				{
					var user = Fastenal.Expo.Web.Helper.UserIdentity.CreateUserIdentity(User.Identity);
					<ul class="nav navbar-nav navbar-right">
						@if (user.Role == "E")
						{
							<li><a href="#">Hello @user.DisplayName (@user.Role)!</a></li>
						}
						else
						{
							<li><a asp-controller="Identity" asp-action="EditProfile">Hello @user.DisplayName (@user.Role)!</a></li>
						}
						<li><a asp-controller="Identity" asp-action="SignOut">Sign out</a></li>
					</ul>
				}
				else
				{
					<ul class="nav navbar-nav navbar-right">
						<li><a asp-controller="Identity" asp-action="SignIn">Sign in</a></li>
					</ul>
				}
			</div>
		</div>
	</nav>
	<div class="container body-content">
		@RenderBody()
		<hr />
		<footer>
			<p>&copy; 2018 - AuthTest</p>
		</footer>
	</div>
	<environment include="Development">
		<script src="~/lib/jquery/dist/jquery.js"></script>
		<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
		<script src="~/js/site.js" asp-append-version="true"></script>
	</environment>
	<environment exclude="Development">
		<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
				asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
				asp-fallback-test="window.jQuery"
				crossorigin="anonymous"
				integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
		</script>
		<script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
				asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
				asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
				crossorigin="anonymous"
				integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
		</script>
		<script src="~/js/site.min.js" asp-append-version="true"></script>
	</environment>
	@RenderSection("Scripts", required: false)
</body>
</html>